### PR TITLE
🔧 MAINTAIN: Update repo

### PR DESCRIPTION
**Pull request by chrisjsewell**
- Add tox.ini
- Add check-manifest to pre-commit
- add development instuctions to README
- Add apidoc and fix documentation warnings
- Add RTD configuration file
- Move docs CI to RTD
- add docker-compose for rabbitmq
- add CI upload to Codecov
- Add CI testing of multiple versions of rabbitmq
- Add PyPi deployment GitHub workflow

### CODE REVIEW

**Comment by chrisjsewell** [comment]
@muhrin can you add me as a maintainer of https://pypi.org/project/kiwipy/ (I'm https://pypi.org/user/cjsewell/)

**Comment by sphuber** [comment]
> @muhrin can you add me as a maintainer of https://pypi.org/project/kiwipy/ (I'm https://pypi.org/user/cjsewell/)

done

**Comment by chrisjsewell** [comment]
cheers!

**Comment by chrisjsewell** [comment]
@sphuber any objections before I merge this?

**Comment by sphuber** [comment]
Nah man, take over the wheel!

**Comment by chrisjsewell** [comment]
🚗 broom broom

**Comment by muhrin** [comment]
Awesome, thansk @chrisjsewell !

**Pull request merged**
