### PR TITLE
Python 3 updates and custom queues

### PR DESCRIPTION
**Pull request by muhrin**
Converted to py3 syntax for everything.
Added the ability to create custom task queues.

### CODE REVIEW

**Comment by muhrin** [comment]
Would be great if you could have a look @sphuber and crucially check that everything still works in AiiDA.  As far as I can remember I didn't change the API only add things.

**Comment by sphuber** [comment]
Thanks a lot @muhrin . I checked it out locally and ran the tests of the develop branch of `aiida-core`. The only problem is that you have moved the exceptions from `kiwipy.communications` to `kiwipy.exceptions`. This is a breaking change. There might be other ones but at least they are not caught by the unit tests. Furthermore I noticed that there are some `from __future__` statements that got snuck in here. I will go over the code in more detail to see if I can spot more py2 compatibility code that can be removed.

P.S.: is there a reason you moved to line length of 100? All `aiidateam` repos maintain 120 and it would be good if we could keep this consistent.

**Comment by muhrin** [comment]
Thanks @sphuber ! Ok, 
1) Removed the errant `__future__` and and reran your find/replace py2 scripts (no hits)
2) Put in a wildcard import in `communications` to make exceptions accessible from there
3) Changed line length back to 120.  I was sturiggling with 120 with the screen layout I'm using so I changed to 100 for most of my code but I don't do much on kiwi so it's fine if it stays as it was.

**Comment by muhrin** [comment]
Hey @sphuber , any chance we can get this merged?  For me I could really do with a release of this for a project on my side.  Happy to do the release once this is merged.

**Comment by sphuber** [comment]
I can take a look and probably merge it tomorrow. Regarding the changes, you are essentially tackling two different things here correct? Using Python 3 syntax only, and adding a new feature. Do you want to rebase this and create two separate commits to have it a bit clearer of what changes are for what, or do we just squash everything?

**Comment by sphuber** [comment]
Also, I take it this should go into a `0.6.0` release then?

**Comment by muhrin** [comment]
Hey Seb.  Thanks dude.  I'm happy to split it up.  I'll get on it later today.
Yes, 0.6.0 seems appropriate given the py3 syntax update.

**Comment by sphuber** [comment]
@muhrin thanks for all the work dude. Before I start reviewing, I think it would be really useful if we can separate the work in consistent commits. Right now there are a lot of changes and it is a bit difficult to ascertain at times which are merely python syntax changes and what is new functionality.  Could you maybe rebase this and recreate three/four commits:

* Remove remaining python 2 compatibility code
* Update miscellaneous: testing config, docs, README, etc..
* Add new feature to define custom queues

Would this be too difficult/much work? If so, I'd be happy to take a stab at it.

**Comment by muhrin** [comment]
Closing this for now, but I'll be back with segmented PRs and then we can put together the release.

**Pull request closed without merging**
