### PR TITLE
Lazily create and connect resources for `RmqCommunicator` 

### LINKED ISSUE #52: `RmqThreadCommunicator` does not work with recent version of Jupyter
Starting from `notebook==6.0.0`, the `RmqThreadCommunicator` cannot be used in a Jupyter notebook because both applications will try to use the same event loop. This leads to the following exception:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-4798024621a1> in <module>
      1 import kiwipy
      2 
----> 3 comm = kiwipy.connect('amqp://127.0.0.1')
      4 
      5 

~/code/aiida/env/dev/kiwipy/kiwipy/communicate.py in connect(uri, **kwargs)
      8     if uri.startswith('amqp'):
      9         from . import rmq  # Avoid circular ref: pylint: disable=import-outside-toplevel
---> 10         return rmq.connect(connection_params=uri, **kwargs)
     11 
     12     raise ValueError("Uknown communicator uri '{}'".format(uri))

~/code/aiida/env/dev/kiwipy/kiwipy/rmq/threadcomms.py in connect(connection_params, connection_factory, loop, message_exchange, task_exchange, task_queue, task_prefetch_size, task_prefetch_count, encoder, decoder, testing_mode)
    332                                          encoder=encoder,
    333                                          decoder=decoder,
--> 334                                          testing_mode=testing_mode)

~/code/aiida/env/dev/kiwipy/kiwipy/rmq/threadcomms.py in connect(cls, connection_params, connection_factory, loop, message_exchange, task_exchange, task_queue, task_prefetch_size, task_prefetch_count, encoder, decoder, testing_mode, async_task_timeout)
     56 
     57         # Run the loop to create the connection
---> 58         connection = loop.run_until_complete(connection_factory(**connection_params))
     59         comm = cls(connection,
     60                    message_exchange=message_exchange,

/usr/lib/python3.7/asyncio/base_events.py in run_until_complete(self, future)
    561         """
    562         self._check_closed()
--> 563         self._check_runnung()
    564 
    565         new_task = not futures.isfuture(future)

/usr/lib/python3.7/asyncio/base_events.py in _check_runnung(self)
    524         if events._get_running_loop() is not None:
    525             raise RuntimeError(
--> 526                 'Cannot run the event loop while another loop is running')
    527 
    528     def run_forever(self):

RuntimeError: Cannot run the event loop while another loop is running

```

### LINKED ISSUE #56: Make connecting of Communicator resources lazy
Currently the publisher, subscriber and task queue are always connected when the communicator is connected, but not all three are always needed. Since connecting is a relatively heavy operation, it is better to connect them lazily.

### PR DESCRIPTION
**Pull request by muhrin**
Fixes #56 

The communicator is passed a connection but doesn't create the relevant
queues until the user carried out an action that needs one of them to
exist, such as sending a message or requesting a publisher or subscriber.
Because of this laziness, the `RmqThreadCommunicator`, and other clients
don't see the change. The only aspect that has had to change is the
getters for publisher/subscriber and the task queue which have now
become coroutines. This is necessary to await their connection being
created the first time they are created.

### CODE REVIEW

**Comment by sphuber** [comment]
@muhrin I merged the other PR and rebased this. I created a corresponding issue for easy tracking. There is one problem with backwards-compatibility that I can already see and that is that you removed the `stop` method of the threadcomm. We actually call this. I can reinstate it with a deprecation warning and forward the call to `close`. I will do this locally and see if the rest of the tests of `aiida-core` run with these changes.

**Comment by muhrin** [comment]
Thanks SP!  I see, I see.  So, we *could* forward `stop` to `close` however it needs to be clear that the functionality is different (and in fact I'm removing `stop` because it wasn't particularly safe).  Basically `close` is to make up for python's lack of a proper destructor.  Once you call it that's it, you can't use the obejct again.  With `stop` you could have called `start` again and it _may_ have functioned correctly (but it wasn't tested).  So, to keep things simple we now just ask users to create another instance if they want to communicate again.

**Comment by muhrin** [comment]
Let me know what you think.  Also, any idea why this is failing the notebook test?

**Comment by sphuber** [comment]
So you propose to reinstate the stop method but just have it raise? This will break `aiida-core` for one. Might not be a problem necessarily as I think it should not install it automatically and we can up the requirement plus adapt our usage in the next release

**Comment by muhrin** [comment]
Well maybe a compromise is to do as you originally suggested: put a depracation warning on `stop()` and plum it to a `close()`, however make `start()` raise as this is really where the newly unsupported behaviour begins.

**Comment by sphuber** [comment]
Regarding the failing notebook test: it fails at `connect_factory(**connection_params)` and it seems that `connection_params` is a string. This could make sense, since you started supporting both a dictionary as well as a full qualified string URI no?
Will look a bit in detail

**Comment by sphuber** [comment]
@muhrin found the problem for the failing notebook: had to make a change in `kiwipy/communicate.py `. Please check if that is what you would have expected.

**Comment by muhrin** [comment]
Thanks Seb, I also found this mistake and have fixed it locally but I'd rather fix it the way that I have which is in `rmq/communicator.py`'s `async_connect()` as this is the final point we hand off to `aio_pika` and therefore all routes to creating a communicator will benefit.  I've also made it so that whatever is in `connection_params` is simply passed to the connection factory, essentially without interpretation, meaning that if `aio_pika` change their interface we don't change `kiwipy`, just clients of `kiwipy`.

I'm happy to put it in when I have a look at the general issues this afternoon but if want to change it now, here's the snippet:

```
    connection_params = connection_params or {}
    if isinstance(connection_params, dict):
        connection = await connection_factory(**connection_params)
    else:
        connection = await connection_factory(connection_params)

    communicator = RmqCommunicator(
        connection=connection,

        # Messages
        message_exchange=message_exchange,
```

**Comment by sphuber** [comment]
You can go ahead and fix it when you do the other changes as well, no problem.

**Comment by muhrin** [comment]
Ok, @sphuber , this one is good to go from my side.  I added my solution to the whole URI string issue.  PR for deprecating stop/start coming on top of this one.

**Pull request merged**
